/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.esi.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Objects;

/**
 * factory_details object
 */
@ApiModel(description = "factory_details object")
public class PlanetFactoryDetails implements Serializable {
    private static final long serialVersionUID = 1L;

    @JsonProperty("schematic_id")
    private Integer schematicId = null;

    public PlanetFactoryDetails schematicId(Integer schematicId) {
        this.schematicId = schematicId;
        return this;
    }

    /**
     * schematic_id integer
     * 
     * @return schematicId
     **/
    @ApiModelProperty(example = "null", required = true, value = "schematic_id integer")
    public Integer getSchematicId() {
        return schematicId;
    }

    public void setSchematicId(Integer schematicId) {
        this.schematicId = schematicId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PlanetFactoryDetails planetFactoryDetails = (PlanetFactoryDetails) o;
        return Objects.equals(this.schematicId, planetFactoryDetails.schematicId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(schematicId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PlanetFactoryDetails {\n");

        sb.append("    schematicId: ").append(toIndentedString(schematicId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
